# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sjappas

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://mcr.microsoft.com/
          username: ${{ secrets.AzureAppService_ContainerUsername_f42ed4b8c68949eb818e2aaef1039a38 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_d3e570a118214a039557037ab357fd50 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_f42ed4b8c68949eb818e2aaef1039a38 }}/appsvc/wordpress-alpine-php:${{ github.sha }}
          file: ./Dockerfile

    deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'sjappas'
            slot-name: 'production'
            publish-profile: ${{ secrets.AzureAppService_PublishProfile_8c9864edf1cf4626b55700daf13b8863 }}
            images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_f42ed4b8c68949eb818e2aaef1039a38 }}/appsvc/wordpress-alpine-php:${{ github.sha }}'
